/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Michelle.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Michelle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ch03.geometry} material={materials.Ch03_Body} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Michelle.glb')
